version: "3.8"

services:
  ipfs-single:
    image: ipfs/kubo:latest
    container_name: ipfs-single
    restart: unless-stopped
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-single-data:/data/ipfs
    networks:
      - ipfs-network

networks:
  ipfs-network:
    driver: bridge

volumes:
  ipfs-single-data: